### PR TITLE
Repo standardization

### PR DESCRIPTION
**Pull request by ryanml**
* Enforcing Node at version 12 via the package file
* Adding basic .gitattributes file
* Adding basic .editorconfig file
* Updating readme to reference yarn over npm

Related: https://github.com/MetaMask/MetaMask-planning/issues/32

### CODE REVIEW

**Comment by ryanml** [comment]
cc @rekmarks, per https://github.com/MetaMask/extensionizer/pull/22 and this PR's pending CI status, is there perhaps an allowance that needs to be made in the repo settings?

**Review by ryanml — COMMENTED** [review]
also, note on branch naming

**Comment by Gudahtt** [comment]
It would be nice to clean up the `.gitignore` as well. We should at least be ignoring the `yarn-debug.log` files.

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Review by Gudahtt — APPROVED** [review]

**Comment by rekmarks** [comment]
CI is passing: https://app.circleci.com/pipelines/github/MetaMask/extensionizer/10/workflows/6f483a37-92ac-4394-a91b-db8ddb1cba3c

**Pull request merged**
